version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

    commands:
      #install npm
      - npm install

  build:
    commands:
      # run build script
      - npm run build

artifacts:
  files:
    - assest/**/*
    - pages/**/*
    - pulbic/**/*
    - scripts/**/*
    - styles/**/*
    - .eslintrc.json
    - .gitignore
    - appspec.yml
    - buildspec.yml
    - next.config.js
    - package-lock.json
    - package.json
    - README.md
    - tsconfig.json
