version: 2.0

phases:
  install:
    runtime-versions:
      nodejs: 14

    commands:
      #install npm
      - npm install

    build:
      commands:
        # run build script
        - npm run build

  artifacts:
    files:
      - assest/**/*
      - component/**/*
      - pages/**/*
      - pulbic/**/*
      - scripts/**/*
      - settings/**/*
      - styles/**/*
      # - jsconfig.json
      - package.json
      - appspec.yml
      # - postcss.config.js
      # - taiwind.config.js
