import Head from 'next/head'
import Image from 'next/image'
import { use, useEffect, useState } from 'react'
import styles from '../styles/Home.module.scss'

export default function Home() {

  const [board, setBoard] = useState(new Array(9).fill(null))
  const [isFirst, setIsFirst] = useState(false)
  const [isWinner, setIsWinner] = useState<'X' | 'O' | null>(null)

  useEffect(() => {
    console.log(111)
    fetch(`https://9quexvb624.execute-api.ap-southeast-1.amazonaws.com/dev`, {
      method: "POST",
      headers: {},
      body: JSON.stringify({ firstName: "abc", lastName: "bcd" }),
    }).then((res) => console.log(res));
  }, [])

  useEffect(() => {
    const listCheck: any = {
      1: [
        [2, 3],
        [4, 7],
        [5, 9]
      ],
      2: [
        [5, 8]
      ],
      3: [
        [5, 7],
        [6, 9]
      ],
      4: [
        [5, 6]
      ],
      7: [
        [8, 9]
      ]
    }
    for (let i in board) {
      if (!!board[i]) {
        const pointSelect = listCheck[+i + 1] || []
        for (let list of pointSelect) {
          let count = 0
          for (let item of list) {
            if (board[item - 1] == board[i]) {
              if (!count)
                count++
              else {
                setIsWinner(board[i])
              }
            }
          }
        }
      }
    }
  }, [board])

  function onClick(index: number) {
    return () => {
      if (!isWinner) {
        if (!board[index]) {
          const boardTemp = [...board]
          boardTemp[index] = isFirst ? 'X' : 'O'
          setBoard(boardTemp)
          setIsFirst(prevState => !prevState)
        }
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          board.map((point, index) => <span className={styles[point?.toLowerCase() || '']} onClick={onClick(index)} key={index}></span>)
        }
      </main>
      {isWinner && <p>Winner is {isWinner}</p>}

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
